# Generated by Django 6.1.1 on 2026-09-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrecioServicio',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
